# Generated by Django 4.2.18 on 2026-01-29 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annee',
            fields=[
                ('id_annee', models.AutoField(primary_key=True, serialize=False)),
                ('debut', models.IntegerField(blank=True, null=True)),
                ('fin', models.IntegerField(blank=True, null=True)),
                ('annee', models.CharField(max_length=20)),
                ('etat_annee', models.CharField(max_length=50)),
                ('date_ouverture', models.DateField()),
                ('date_cloture', models.DateField()),
            ],
            options={
                'db_table': 'annee',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AttributionType',
            fields=[
                ('id_attribution_type', models.AutoField(primary_key=True, serialize=False)),
                ('attribution_type', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'attribution_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id_campus', models.AutoField(primary_key=True, serialize=False)),
                ('campus', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=255)),
                ('localisation', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'campus',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClasseActive',
            fields=[
                ('id_classe_active', models.AutoField(primary_key=True, serialize=False)),
                ('groupe', models.CharField(blank=True, max_length=10, null=True)),
                ('isterminale', models.IntegerField(db_column='isTerminale')),
            ],
            options={
                'db_table': 'classe_active',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClasseCycle',
            fields=[
                ('id_cycle', models.AutoField(primary_key=True, serialize=False)),
                ('cycle', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'classe_cycle',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClasseCycleActif',
            fields=[
                ('id_cycle_actif', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('cycle_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.classecycle')),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.campus')),
            ],
            options={
                'db_table': 'classe_cycle_actif',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id_classe', models.AutoField(primary_key=True, serialize=False)),
                ('classe', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'classes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id_cours', models.AutoField(primary_key=True, serialize=False)),
                ('cours', models.CharField(max_length=150)),
                ('code_cours', models.CharField(blank=True, max_length=15, null=True)),
                ('domaine', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cours',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CoursParClasse',
            fields=[
                ('id_cours_classe', models.AutoField(primary_key=True, serialize=False)),
                ('ponderation', models.IntegerField(blank=True, null=True)),
                ('cm', models.IntegerField(blank=True, db_column='CM', null=True)),
                ('td', models.IntegerField(blank=True, db_column='TD', null=True)),
                ('tp', models.IntegerField(blank=True, db_column='TP', null=True)),
                ('tpe', models.IntegerField(blank=True, db_column='TPE', null=True)),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.campus')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.classeactive')),
                ('id_cours', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.cours')),
                ('id_cycle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.classecycleactif')),
            ],
            options={
                'db_table': 'cours_par_classe',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DeliberationAnnuelleConditions',
            fields=[
                ('id_decision', models.AutoField(primary_key=True, serialize=False)),
                ('sigle', models.CharField(max_length=10)),
                ('decision', models.CharField(max_length=50)),
                ('pourcentage_requis_reussite', models.IntegerField()),
                ('max_echecs_acceptable', models.IntegerField()),
                ('seuil_profondeur_echec', models.IntegerField()),
                ('sanction_disciplinaire', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'deliberation_annuelle_conditions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DeliberationAnnuelleFinalites',
            fields=[
                ('id_finalite', models.AutoField(primary_key=True, serialize=False)),
                ('finalite', models.CharField(max_length=50)),
                ('droit_avancement', models.IntegerField()),
            ],
            options={
                'db_table': 'deliberation_annuelle_finalites',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id_diplome', models.AutoField(primary_key=True, serialize=False)),
                ('diplome', models.CharField(max_length=50, unique=True)),
                ('sigle', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'diplome',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id_ecole', models.AutoField(primary_key=True, serialize=False)),
                ('nom_ecole', models.CharField(max_length=250)),
                ('sigle', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('domaine', models.CharField(max_length=50)),
                ('site', models.CharField(max_length=50)),
                ('logo_ecole', models.CharField(blank=True, max_length=100, null=True)),
                ('logo_ministere', models.CharField(blank=True, max_length=100, null=True)),
                ('siege', models.CharField(max_length=50)),
                ('fax', models.CharField(max_length=20)),
                ('representant', models.CharField(max_length=50)),
                ('b_postale', models.CharField(max_length=50)),
                ('emplacement', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ecole',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id_eleve', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('etat_civil', models.CharField(blank=True, max_length=50, null=True)),
                ('code_eleve', models.CharField(blank=True, max_length=250, null=True)),
                ('code_annee', models.IntegerField(blank=True, null=True)),
                ('matricule', models.CharField(blank=True, max_length=50, null=True)),
                ('nom_pere', models.CharField(blank=True, max_length=200, null=True)),
                ('prenom_pere', models.CharField(blank=True, max_length=200, null=True)),
                ('nom_mere', models.CharField(blank=True, max_length=200, null=True)),
                ('prenom_mere', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('email_parent', models.CharField(blank=True, max_length=254, null=True)),
                ('password_parent', models.CharField(blank=True, max_length=300, null=True)),
                ('password', models.CharField(blank=True, max_length=300, null=True)),
                ('tutaire', models.CharField(blank=True, max_length=250, null=True)),
                ('telephone', models.CharField(blank=True, max_length=128, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('naissance_region', models.CharField(blank=True, max_length=30, null=True)),
                ('naissance_pays', models.CharField(blank=True, max_length=30, null=True)),
                ('naissance_province', models.CharField(blank=True, max_length=30, null=True)),
                ('naissance_commune', models.CharField(blank=True, max_length=30, null=True)),
                ('naissance_zone', models.CharField(blank=True, max_length=30, null=True)),
                ('province_actuelle', models.CharField(blank=True, max_length=20, null=True)),
                ('commune_actuelle', models.CharField(blank=True, max_length=20, null=True)),
                ('zone_actuelle', models.CharField(blank=True, max_length=20, null=True)),
                ('imageurl', models.CharField(blank=True, db_column='imageUrl', max_length=100, null=True)),
                ('nationalite', models.CharField(blank=True, max_length=50, null=True)),
                ('professionpere', models.CharField(blank=True, db_column='professionPere', max_length=100, null=True)),
                ('professionmere', models.CharField(blank=True, db_column='professionMere', max_length=100, null=True)),
                ('profsion_tutaire', models.CharField(blank=True, max_length=100, null=True)),
                ('idelivrancelieuetdate', models.CharField(blank=True, db_column='IDelivranceLieuEtDate', max_length=100, null=True)),
                ('code_secret_parent', models.CharField(blank=True, max_length=250, null=True)),
                ('code_secret_eleve', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'eleve',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EleveNoteType',
            fields=[
                ('id_type_note', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=250)),
                ('sigle', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'eleve_note_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id_horaire', models.AutoField(primary_key=True, serialize=False)),
                ('jour', models.CharField(max_length=100)),
                ('debut', models.CharField(max_length=100)),
                ('fin', models.CharField(max_length=100)),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.campus')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.classeactive')),
                ('id_cours', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.coursparclasse')),
                ('id_cycle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.classecycleactif')),
            ],
            options={
                'db_table': 'horaire',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HoraireType',
            fields=[
                ('id_horaire_type', models.AutoField(primary_key=True, serialize=False)),
                ('horaire_type', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'horaire_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id_mention', models.AutoField(primary_key=True, serialize=False)),
                ('mention', models.CharField(max_length=30)),
                ('abbreviation', models.CharField(max_length=5)),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
            ],
            options={
                'db_table': 'mention',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id_module', models.AutoField(primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('url_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'module',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id_parent', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(max_length=250)),
                ('telephone', models.CharField(max_length=128, unique=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=300)),
                ('code_secret_parent', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'parent',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ParentOperation',
            fields=[
                ('id_operation', models.AutoField(primary_key=True, serialize=False)),
                ('libelle_operation', models.CharField(max_length=250)),
                ('code_action', models.CharField(blank=True, max_length=100, null=True)),
                ('icone_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'parent_operations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id_personnel', models.AutoField(primary_key=True, serialize=False)),
                ('codeannee', models.CharField(blank=True, db_column='codeAnnee', max_length=200, null=True)),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('genre', models.CharField(max_length=22)),
                ('etat_civil', models.CharField(max_length=200)),
                ('type_identite', models.CharField(max_length=200)),
                ('numero_identite', models.CharField(blank=True, max_length=20, null=True)),
                ('telephone', models.CharField(blank=True, max_length=128, null=True)),
                ('region', models.CharField(blank=True, max_length=200, null=True)),
                ('pays', models.CharField(blank=True, max_length=200, null=True)),
                ('province', models.CharField(max_length=200)),
                ('commune', models.CharField(max_length=200)),
                ('code_secret', models.TextField(blank=True, null=True)),
                ('zone', models.CharField(max_length=200)),
                ('addresse', models.CharField(max_length=200)),
                ('imageurl', models.CharField(blank=True, db_column='imageUrl', max_length=100, null=True)),
                ('ismaitresse', models.IntegerField(db_column='isMaitresse')),
                ('isinstiteur', models.IntegerField(db_column='isInstiteur')),
                ('isdaf', models.IntegerField(db_column='isDAF')),
                ('isdirecteur', models.IntegerField(db_column='isDirecteur')),
                ('isuser', models.IntegerField(db_column='isUser')),
                ('en_fonction', models.IntegerField()),
                ('is_verified', models.IntegerField()),
            ],
            options={
                'db_table': 'personnel',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PersonnelCategorie',
            fields=[
                ('id_personnel_category', models.AutoField(primary_key=True, serialize=False)),
                ('categorie', models.CharField(max_length=50, unique=True)),
                ('sigle', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'personnel_categorie',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PersonnelType',
            fields=[
                ('id_type_personnel', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50, unique=True)),
                ('sigle', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'personnel_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PosteAdministratif',
            fields=[
                ('id_posteAdministratif', models.AutoField(primary_key=True, serialize=False)),
                ('poste', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'personnel_posteAdministratif',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id_session', models.AutoField(primary_key=True, serialize=False)),
                ('session', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'session',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id_specialite', models.AutoField(primary_key=True, serialize=False)),
                ('specialite', models.CharField(max_length=200)),
                ('sigle', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'specialite',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TacheEnseignant',
            fields=[
                ('id_tache', models.AutoField(primary_key=True, serialize=False)),
                ('tache', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'personnelEnseignant_Taches',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Trimestre',
            fields=[
                ('id_trimestre', models.AutoField(primary_key=True, serialize=False)),
                ('trimestre', models.CharField(max_length=20)),
                ('etat_trimestre', models.CharField(max_length=50)),
                ('date_ouverture', models.DateField()),
                ('date_cloture', models.DateField()),
            ],
            options={
                'db_table': 'trimestre',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id_vacation', models.AutoField(primary_key=True, serialize=False)),
                ('vacation', models.CharField(max_length=20)),
                ('sigle', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'vacation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsersOtherModule',
            fields=[
                ('id_user_per_module', models.AutoField(primary_key=True, serialize=False)),
                ('id_module', models.IntegerField()),
                ('user', models.IntegerField()),
                ('id_personnel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.personnel')),
            ],
            options={
                'db_table': 'users_other_module',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserModule',
            fields=[
                ('id_user_module', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.IntegerField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.personnel')),
            ],
            options={
                'db_table': 'user_module',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserEnseignement',
            fields=[
                ('id_user_enseignant', models.AutoField(primary_key=True, serialize=False)),
                ('canmodify', models.IntegerField(db_column='canModify')),
                ('canonlyview', models.IntegerField(db_column='canOnlyView')),
                ('classe_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.classeactive')),
                ('cycle_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.classecycleactif')),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.campus')),
                ('id_personnel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.personnel')),
            ],
            options={
                'db_table': 'user_enseignement',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id_salle', models.AutoField(primary_key=True, serialize=False)),
                ('salle', models.CharField(max_length=250)),
                ('partage', models.IntegerField()),
                ('capacite', models.IntegerField()),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.campus')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.classeactive')),
                ('id_cycle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.classecycleactif')),
            ],
            options={
                'db_table': 'salle',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id_prestation', models.AutoField(primary_key=True, serialize=False)),
                ('heured', models.CharField(db_column='heureD', max_length=20)),
                ('heuref', models.CharField(db_column='heureF', max_length=20)),
                ('id_horaire', models.IntegerField()),
                ('id_etudiant', models.IntegerField()),
                ('id_personnel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.personnel')),
            ],
            options={
                'db_table': 'prestation',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='personnel',
            name='id_categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.personnelcategorie'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='id_diplome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.diplome'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='id_personnel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.personneltype'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='id_posteAdministratif',
            field=models.ForeignKey(blank=True, db_column='id_posteAdministratif', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.posteadministratif'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='id_specialite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.specialite'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='id_tache',
            field=models.ForeignKey(blank=True, db_column='id_tache', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.tacheenseignant'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='id_vacation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.vacation'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id_periode', models.AutoField(primary_key=True, serialize=False)),
                ('periode', models.CharField(max_length=20)),
                ('etat_periode', models.CharField(max_length=50)),
                ('id_trimestre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.trimestre')),
            ],
            options={
                'db_table': 'periode',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HorairePresence',
            fields=[
                ('id_horaire_presence', models.AutoField(primary_key=True, serialize=False)),
                ('present_ou_absent', models.IntegerField()),
                ('date_presence', models.DateField()),
                ('si_absent_motif', models.CharField(blank=True, max_length=255, null=True)),
                ('id_eleve', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.eleve')),
                ('id_horaire', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.horaire')),
            ],
            options={
                'db_table': 'horaire_presence',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='horaire',
            name='id_horaire_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.horairetype'),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id_evaluation', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('ponderer_eval', models.PositiveIntegerField()),
                ('date_eval', models.DateField()),
                ('date_soumission', models.DateField(blank=True, null=True)),
                ('contenu_evaluation', models.CharField(max_length=100)),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.campus')),
                ('id_classe_active', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.classeactive')),
                ('id_cours_classe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.coursparclasse')),
                ('id_cycle_actif', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.classecycleactif')),
                ('id_periode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.periode')),
                ('id_session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.session')),
                ('id_trimestre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.trimestre')),
                ('id_type_note', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.elevenotetype')),
            ],
            options={
                'db_table': 'evaluation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EleveNote',
            fields=[
                ('id_note', models.AutoField(primary_key=True, serialize=False)),
                ('date_saisie', models.DateField()),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.campus')),
                ('id_classe_active', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.classeactive')),
                ('id_cours_classe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.coursparclasse')),
                ('id_cycle_actif', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.classecycleactif')),
                ('id_eleve', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.eleve')),
                ('id_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.evaluation')),
                ('id_periode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.periode')),
                ('id_session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.session')),
                ('id_trimestre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.trimestre')),
                ('id_type_note', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.elevenotetype')),
            ],
            options={
                'db_table': 'eleve_note',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EleveInscription',
            fields=[
                ('id_inscription', models.AutoField(primary_key=True, serialize=False)),
                ('date_inscription', models.DateField()),
                ('status', models.IntegerField()),
                ('redoublement', models.IntegerField()),
                ('isdelegue', models.IntegerField(db_column='isDelegue')),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.campus')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.classeactive')),
                ('id_classe_cycle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.classecycleactif')),
                ('id_eleve', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.eleve')),
                ('id_trimestre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.trimestre')),
            ],
            options={
                'db_table': 'eleve_inscription',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EleveConduite',
            fields=[
                ('id_eleve_conduite', models.AutoField(primary_key=True, serialize=False)),
                ('motif', models.CharField(max_length=255)),
                ('quote', models.PositiveIntegerField()),
                ('date_enregistrement', models.DateField()),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.campus')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.classeactive')),
                ('id_cycle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.classecycleactif')),
                ('id_eleve', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.eleve')),
                ('id_horaire', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.horaire')),
                ('id_periode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.periode')),
                ('id_session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.session')),
                ('id_trimestre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.trimestre')),
            ],
            options={
                'db_table': 'eleve_conduite',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='eleve',
            name='id_parent',
            field=models.ForeignKey(blank=True, db_column='id_parent', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.parent'),
        ),
        migrations.CreateModel(
            name='DeliberationTrimistrielleResultats',
            fields=[
                ('id_deliberation', models.AutoField(primary_key=True, serialize=False)),
                ('groupe', models.CharField(max_length=3)),
                ('pourcentage', models.FloatField()),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.campus')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.classeactive')),
                ('id_cycle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.classecycleactif')),
                ('id_decision', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.deliberationannuelleconditions')),
                ('id_eleve', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.eleve')),
                ('id_mention', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.mention')),
            ],
            options={
                'db_table': 'deliberation_trimistrielle_resultats',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DeliberationPeriodiqueResultats',
            fields=[
                ('id_deliberation', models.AutoField(primary_key=True, serialize=False)),
                ('pourcentage', models.FloatField()),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.campus')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.classeactive')),
                ('id_cycle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.classecycleactif')),
                ('id_decision', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.deliberationannuelleconditions')),
                ('id_eleve', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.eleve')),
                ('id_mention', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.mention')),
            ],
            options={
                'db_table': 'deliberation_periodique_resultats',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DeliberationAnnuelleResultats',
            fields=[
                ('id_deliberation', models.AutoField(primary_key=True, serialize=False)),
                ('groupe', models.CharField(max_length=3)),
                ('pourcentage', models.FloatField()),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.campus')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.classeactive')),
                ('id_cycle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.classecycleactif')),
                ('id_decision', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.deliberationannuelleconditions')),
                ('id_eleve', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.eleve')),
                ('id_mention', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.mention')),
                ('id_session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.session')),
            ],
            options={
                'db_table': 'deliberation_annuelle_resultats',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='deliberationannuelleconditions',
            name='id_finalite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.deliberationannuellefinalites'),
        ),
        migrations.CreateModel(
            name='ClasseSection',
            fields=[
                ('id_section', models.AutoField(primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=100)),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.campus')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.classeactive')),
                ('id_cycle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.classecycleactif')),
            ],
            options={
                'db_table': 'classe_section',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClasseDeliberation',
            fields=[
                ('id_deliberation', models.AutoField(primary_key=True, serialize=False)),
                ('date_deliberation', models.DateField()),
                ('showresults', models.IntegerField(db_column='showResults')),
                ('showsresultsenordre', models.IntegerField(db_column='showsResultsEnOrdre')),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.campus')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.classeactive')),
                ('id_cycle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.classecycleactif')),
                ('id_session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.session')),
            ],
            options={
                'db_table': 'classe_deliberation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClasseActiveResponsable',
            fields=[
                ('id_classe_active_resp', models.AutoField(primary_key=True, serialize=False)),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.campus')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.classeactive')),
                ('id_cycle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.classecycleactif')),
                ('id_personnel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.personnel')),
            ],
            options={
                'db_table': 'classe_active_responsable',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='classeactive',
            name='classe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.classes'),
        ),
        migrations.AddField(
            model_name='classeactive',
            name='cycle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.classecycleactif'),
        ),
        migrations.AddField(
            model_name='classeactive',
            name='id_annee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.annee'),
        ),
        migrations.AddField(
            model_name='classeactive',
            name='id_campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.campus'),
        ),
        migrations.CreateModel(
            name='AttributionCours',
            fields=[
                ('id_attribution', models.AutoField(primary_key=True, serialize=False)),
                ('attribution_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.attributiontype')),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.campus')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.classeactive')),
                ('id_cours', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.coursparclasse')),
                ('id_cycle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.classecycleactif')),
                ('id_personnel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.personnel')),
            ],
            options={
                'db_table': 'attribution_cours',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AnneeTrimestre',
            fields=[
                ('id_trimestre', models.AutoField(primary_key=True, serialize=False)),
                ('debut', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.campus')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.classeactive')),
                ('id_cycle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.classecycleactif')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.trimestre')),
            ],
            options={
                'db_table': 'annee_trimestre',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AnneePeriode',
            fields=[
                ('id_periode', models.AutoField(primary_key=True, serialize=False)),
                ('periode', models.CharField(max_length=50)),
                ('debut', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, null=True)),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.annee')),
                ('id_campus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.campus')),
                ('id_classe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.classeactive')),
                ('id_cycle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.classecycleactif')),
            ],
            options={
                'db_table': 'annee_periode',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CoursParCycle',
            fields=[
                ('id_cours_cycle', models.AutoField(primary_key=True, serialize=False)),
                ('cours_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.cours')),
                ('cycle_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.classecycleactif')),
                ('id_annee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account_creation.annee')),
            ],
            options={
                'db_table': 'cours_par_cycle',
                'managed': True,
                'unique_together': {('cours_id', 'cycle_id', 'id_annee')},
            },
        ),
    ]
